# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weathertest',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('temp', models.FloatField()),
                ('hum', models.FloatField()),
                ('press', models.FloatField()),
                ('dir', models.CharField(max_length=50)),
                ('windspeed', models.FloatField()),
                ('condition', models.CharField(max_length=50)),
            ],
        ),
    ]
