# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionmodel', '0003_celerytest'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryDataTest',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('no', models.IntegerField()),
                ('windspeed', models.FloatField()),
                ('windspeed_30s', models.FloatField()),
                ('windspeed_10m', models.FloatField()),
                ('degree', models.FloatField()),
            ],
        ),
    ]
