# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionmodel', '0004_historydatatest'),
    ]

    operations = [
        migrations.AddField(
            model_name='historydatatest',
            name='power',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
