# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionmodel', '0006_config_realtime_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryData',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('no', models.IntegerField()),
                ('windspeed', models.FloatField()),
                ('power', models.FloatField()),
            ],
        ),
    ]
