# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionmodel', '0007_historydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historydata',
            name='no',
            field=models.IntegerField(primary_key=True),
        ),
    ]
