# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictionmodel', '0008_auto_20171209_1922'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryData',
        ),
    ]
