# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionmodel', '0009_delete_historydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('no', models.IntegerField()),
                ('windspeed', models.FloatField()),
                ('power', models.FloatField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='historydata',
            unique_together=set([('time', 'no')]),
        ),
    ]
