# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictionmodel', '0011_auto_20171211_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtime',
            old_name='id',
            new_name='DataID',
        ),
        migrations.RenameField(
            model_name='realtime',
            old_name='value',
            new_name='DataValue',
        ),
        migrations.RemoveField(
            model_name='realtime',
            name='config',
        ),
    ]
