# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictionmodel', '0012_auto_20171211_1840'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Config',
        ),
    ]
