# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predictionmodel', '0013_delete_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('configname', models.CharField(max_length=20)),
                ('RealtimeItem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='predictionmodel.RealTime')),
            ],
        ),
    ]
