# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predictionmodel', '0014_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='id',
        ),
        migrations.AlterField(
            model_name='config',
            name='RealtimeItem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='predictionmodel.RealTime'),
        ),
    ]
