# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictionmodel', '0015_auto_20171211_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='RealtimeItem',
        ),
        migrations.DeleteModel(
            name='Config',
        ),
    ]
