# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionmodel', '0017_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataTime', models.DateTimeField()),
                ('DataID', models.IntegerField()),
                ('DataValue', models.FloatField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='weatherdata',
            unique_together=set([('DataTime', 'DataID')]),
        ),
    ]
