# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionmodel', '0018_auto_20171211_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResult_16points',
            fields=[
                ('DataTime', models.DateTimeField(primary_key=True, serialize=False)),
                ('DataValue', models.FloatField()),
            ],
        ),
    ]
