# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionmodel', '0019_predictionresult_16points'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResult_288points',
            fields=[
                ('DataTime', models.DateTimeField(primary_key=True, serialize=False)),
                ('DataValue', models.FloatField()),
            ],
        ),
    ]
