# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionmodel', '0020_predictionresult_288points'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTime_GeneraionData',
            fields=[
                ('DataID', models.IntegerField(primary_key=True, serialize=False)),
                ('DataValue', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RealTime_GenerationStatus',
            fields=[
                ('DataID', models.IntegerField(primary_key=True, serialize=False)),
                ('DataValue', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RealTime_WindTower',
            fields=[
                ('DataID', models.IntegerField(primary_key=True, serialize=False)),
                ('DataValue', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RealTime_Write',
            fields=[
                ('DataID', models.IntegerField(primary_key=True, serialize=False)),
                ('DataValue', models.FloatField()),
            ],
        ),
    ]
