# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionmodel', '0022_auto_20171228_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('DataID', models.IntegerField(primary_key=True, serialize=False)),
                ('configname', models.CharField(max_length=20)),
            ],
        ),
    ]
