# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictionmodel', '0023_config'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RealTime_GeneraionData',
            new_name='RealTime_GenerationData',
        ),
    ]
