# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-19 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionmodel', '0024_auto_20171228_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='configname',
            field=models.CharField(max_length=30),
        ),
    ]
