# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-19 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionmodel', '0025_auto_20180219_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTime_Read',
            fields=[
                ('DataID', models.IntegerField(primary_key=True, serialize=False)),
                ('DataValue', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='RealTime_GenerationData',
        ),
        migrations.DeleteModel(
            name='RealTime_GenerationStatus',
        ),
        migrations.DeleteModel(
            name='RealTime_WindTower',
        ),
    ]
