# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-02 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionmodel', '0026_auto_20180219_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResult_16points1',
            fields=[
                ('DataTime', models.DateTimeField(primary_key=True, serialize=False)),
                ('DataValue', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PredictionResult_288points1',
            fields=[
                ('DataTime', models.DateTimeField(primary_key=True, serialize=False)),
                ('DataValue', models.FloatField()),
            ],
        ),
    ]
